#define CAR_CLUSTER_VERSION_MAJOR @CAR_CLUSTER_VERSION_MAJOR @
#define CAR_CLUSTER_VERSION_MINOR @CAR_CLUSTER_VERSION_MINOR @
#define WINDOW_TITLE "Car Cluster"
#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 550
#define WINDOW_STYLE sf::Style::None
#define APPLICATION_FPS 60