#define CAR_CLUSTER_VERSION_MAJOR @CAR_CLUSTER_VERSION_MAJOR @
#define CAR_CLUSTER_VERSION_MINOR @CAR_CLUSTER_VERSION_MINOR @

#define PI 3.14159265358979323846f

#define SKIP_SPLASH true
#define SPLASH_FADEIN_TIME 2.0f
#define SPLASH_FADEOUT_TIME 1.15f

#define WINDOW_TITLE "Car Cluster"
#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 550
#define WINDOW_STYLE sf::Style::Default

#define APPLICATION_FPS 60

#define FORD_LOGO_PATH "assets/ford.png"
#define FONT_PATH "assets/OpenSans-Light.ttf"

#define VELOCIMETER_WIDTH 200
#define VELOCIMETER_HEIGHT 200
#define VELOCIMETER_X WINDOW_WIDTH / 2 - VELOCIMETER_WIDTH / 2
#define VELOCIMETER_Y WINDOW_HEIGHT / 2 - VELOCIMETER_HEIGHT / 2

#define RPM_RADIUS 225
// #define RPM_X WINDOW_WIDTH / 4 * 3 - RPM_WIDTH / 2
// #define RPM_Y WINDOW_HEIGHT / 2 - RPM_HEIGHT / 2
#define RPM_X WINDOW_WIDTH / 2
#define RPM_Y WINDOW_HEIGHT / 2

#define FUEL_WIDTH 100
#define FUEL_HEIGHT 100
#define FUEL_X WINDOW_WIDTH / 1.25f - FUEL_WIDTH / 2
#define FUEL_Y WINDOW_HEIGHT * 0.5f - FUEL_HEIGHT / 2

#define OIL_WIDTH 100
#define OIL_HEIGHT 100
#define OIL_X WINDOW_WIDTH / 1.25f - OIL_WIDTH / 2
#define OIL_Y WINDOW_HEIGHT * 0.75f - OIL_HEIGHT / 2